# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule QuickFSPublicAPI.Model.ApiUsage do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"usage"
  ]

  @type t :: %__MODULE__{
    :"usage" => QuickFSPublicAPI.Model.ApiUsageUsage.t
  }
end

defimpl Poison.Decoder, for: QuickFSPublicAPI.Model.ApiUsage do
  import QuickFSPublicAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"usage", :struct, QuickFSPublicAPI.Model.ApiUsageUsage, options)
  end
end

