# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule QuickFSPublicAPI.Model.ApiUsageUsageQuota do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"used",
    :"remaining",
    :"resets"
  ]

  @type t :: %__MODULE__{
    :"used" => integer(),
    :"remaining" => integer(),
    :"resets" => String.t
  }
end

defimpl Poison.Decoder, for: QuickFSPublicAPI.Model.ApiUsageUsageQuota do
  def decode(value, _options) do
    value
  end
end

