# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule QuickFSPublicAPI.Model.ApiUsageUsage do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"quota"
  ]

  @type t :: %__MODULE__{
    :"quota" => QuickFSPublicAPI.Model.ApiUsageUsageQuota.t | nil
  }
end

defimpl Poison.Decoder, for: QuickFSPublicAPI.Model.ApiUsageUsage do
  import QuickFSPublicAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"quota", :struct, QuickFSPublicAPI.Model.ApiUsageUsageQuota, options)
  end
end

