# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule QuickFSPublicAPI.Model.DatapointError do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"path",
    :"status",
    :"error",
    :"description",
    :"message"
  ]

  @type t :: %__MODULE__{
    :"path" => String.t | nil,
    :"status" => float(),
    :"error" => String.t,
    :"description" => String.t,
    :"message" => String.t | nil
  }
end

defimpl Poison.Decoder, for: QuickFSPublicAPI.Model.DatapointError do
  def decode(value, _options) do
    value
  end
end

