# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule QuickFSPublicAPI.Model.DatapointRangeErrors do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"errors",
    :"data"
  ]

  @type t :: %__MODULE__{
    :"errors" => [QuickFSPublicAPI.Model.DatapointError.t] | nil,
    :"data" => [float()]
  }
end

defimpl Poison.Decoder, for: QuickFSPublicAPI.Model.DatapointRangeErrors do
  import QuickFSPublicAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"errors", :list, QuickFSPublicAPI.Model.DatapointError, options)
  end
end

