# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule QuickFSPublicAPI.Model.Metrics do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"data"
  ]

  @type t :: %__MODULE__{
    :"data" => [QuickFSPublicAPI.Model.Metric.t]
  }
end

defimpl Poison.Decoder, for: QuickFSPublicAPI.Model.Metrics do
  import QuickFSPublicAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"data", :list, QuickFSPublicAPI.Model.Metric, options)
  end
end

