# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule QuickFSPublicAPI.Model.Metric do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"metric",
    :"data_type",
    :"company_types",
    :"periods",
    :"statement_type"
  ]

  @type t :: %__MODULE__{
    :"metric" => String.t,
    :"data_type" => QuickFSPublicAPI.Model.DataType.t,
    :"company_types" => [QuickFSPublicAPI.Model.CompanyType.t],
    :"periods" => [QuickFSPublicAPI.Model.PeriodType.t] | nil,
    :"statement_type" => String.t | nil
  }
end

defimpl Poison.Decoder, for: QuickFSPublicAPI.Model.Metric do
  import QuickFSPublicAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"data_type", :struct, QuickFSPublicAPI.Model.DataType, options)
    |> deserialize(:"company_types", :list, QuickFSPublicAPI.Model.CompanyType, options)
    |> deserialize(:"periods", :list, QuickFSPublicAPI.Model.PeriodType, options)
  end
end

