# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule QuickFSPublicAPI.Api.Companies do
  @moduledoc """
  API calls for all endpoints tagged `Companies`.
  """

  alias QuickFSPublicAPI.Connection
  import QuickFSPublicAPI.RequestBuilder


  @doc """
  List Supported Companies
  Returns a list of ticker symbols supported by QuickFS.net. You may optionally specify a country code (US, CA, MM, AU, NZ, or LN) and an exchange.

  ## Parameters

  - connection (QuickFSPublicAPI.Connection): Connection to server
  - country (String.t): 
  - exchange (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, QuickFSPublicAPI.Model.CompaniesList.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec companies_country_exchange_get(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, QuickFSPublicAPI.Model.RequestError.t} | {:ok, QuickFSPublicAPI.Model.CompaniesList.t} | {:error, Tesla.Env.t}
  def companies_country_exchange_get(connection, country, exchange, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/companies/#{country}/#{exchange}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %QuickFSPublicAPI.Model.CompaniesList{}},
      { 401, %QuickFSPublicAPI.Model.RequestError{}},
      { 403, %QuickFSPublicAPI.Model.RequestError{}}
    ])
  end

  @doc """
  List Recently-Updated Companies
  Returns a list of ticker symbols that were updated with new financial data on or after the specified date (formatted as YYYYMMDD). You may optionally specify a country code (US, CA, MM, AU, NZ, or LN).

  ## Parameters

  - connection (QuickFSPublicAPI.Connection): Connection to server
  - date (String.t): 
  - country (String.t): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, QuickFSPublicAPI.Model.CompaniesList.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec companies_updated_date_country_get(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, QuickFSPublicAPI.Model.RequestError.t} | {:ok, QuickFSPublicAPI.Model.CompaniesList.t} | {:error, Tesla.Env.t}
  def companies_updated_date_country_get(connection, date, country, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/companies/updated/#{date}/#{country}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %QuickFSPublicAPI.Model.CompaniesList{}},
      { 401, %QuickFSPublicAPI.Model.RequestError{}},
      { 403, %QuickFSPublicAPI.Model.RequestError{}}
    ])
  end
end
