# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule QuickFSPublicAPI.Api.Metrics do
  @moduledoc """
  API calls for all endpoints tagged `Metrics`.
  """

  alias QuickFSPublicAPI.Connection
  import QuickFSPublicAPI.RequestBuilder


  @doc """
  List Available Metrics
  Returns a list of available metrics with associated metadata

  ## Parameters

  - connection (QuickFSPublicAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, QuickFSPublicAPI.Model.Metrics.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec metrics_get(Tesla.Env.client, keyword()) :: {:ok, QuickFSPublicAPI.Model.Metrics.t} | {:error, Tesla.Env.t}
  def metrics_get(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/metrics")
    |> Enum.into([])
    |> (&(IO.inspect &1)).()
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %QuickFSPublicAPI.Model.Metrics{}}
    ])
  end
end
