# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule QuickFSPublicAPI.Api.UsageHistory do
  @moduledoc """
  API calls for all endpoints tagged `UsageHistory`.
  """

  alias QuickFSPublicAPI.Connection
  import QuickFSPublicAPI.RequestBuilder


  @doc """
  View API Quota
  Returns your current API usage and limits

  ## Parameters

  - connection (QuickFSPublicAPI.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, QuickFSPublicAPI.Model.ApiUsage.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec usage_get(Tesla.Env.client, keyword()) :: {:ok, QuickFSPublicAPI.Model.RequestError.t} | {:ok, QuickFSPublicAPI.Model.ApiUsage.t} | {:error, Tesla.Env.t}
  def usage_get(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/usage")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %QuickFSPublicAPI.Model.ApiUsage{}},
      { 401, %QuickFSPublicAPI.Model.RequestError{}}
    ])
  end
end
